# render.yaml
services:
  - type: web
    name: ghost-traders-bot
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: TELEGRAM_TOKEN
        fromSecret: true
      - key: SUPABASE_URL
        fromSecret: true
      - key: SUPABASE_KEY
        fromSecret: true
      - key: NOWPAYMENTS_API_KEY
        fromSecret: true
      - key: NOWPAYMENTS_IPN_SECRET
        fromSecret: true
      - key: GROUP_ID
        value: "-1002202662368"
      - key: RENDER_EXTERNAL_URL
        value: "https://ghost-traders-bot.onrender.com"
    healthCheckPath: /health